server:
  port: 8080
#数据库就自行配置了大兄弟
spring:
  datasource:
    url:
    username:
    password:
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.chenchenhui.wx.pay.demo
  configuration:
    map-underscore-to-camel-case: true

wx:
  miniapp:
    appid: #小程序id
    secret: #AppSecret
    aesKey: #微信小程序消息服务器配置的EncodingAESKey
    msgDataFormat: JSON
    mchId: #微信支付商户号
    mchKey:  #微信支付商户密钥
    keyPath: # p12证书的位置 绝对位置相对位置都行
